### PR TITLE
Notebook loading

### PR DESCRIPTION
**Pull request by carlso70**

### CODE REVIEW

**Comment by tkdestroyer1** [comment]
@carlso70 
Please make the file writing safe. Currently, you can write notes to different directories than the notebook's directory, and even overwrite source files (i.e., change the code).

**Comment by carlso70** [comment]
> @carlso70
> Please make the file writing safe. Currently, you can write notes to different directories than the notebook's directory, and even overwrite source files (i.e., change the code).

I refuse

**Comment by carlso70** [comment]
> Please make sure that files have newlines at the end.

add your linter configs first

**Comment by kroppt** [comment]
Is there a reason for including a save notebook function, but not a load notebook function?

**Comment by carlso70** [comment]
@tkdestroyer1 can you create a test for file safety. I think I fixed the issue, but idk

**Pull request merged**
